### ISSUE TITLE
Docs seem to get truncated when viewing on the iPhone 

### ISSUE THREAD

**Issue by girishla** [nodejs/docs#92] opened 2016-03-16 08:07 UTC
Not sure if this is the right place to create this issue but Docs seem to get truncated when viewing on the iPhone 
iOS version 9.2.1

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-16 09:00
Can you send in a screenshot?

**Comment by girishla** [comment] 2016-03-16 09:07
The "Event:error" line is the last I can see in this page. It doesn't allow me to scroll any further. I've tried on Chrome and Safari on multiple iphones. Same behaviour.

![img_0145](https://cloud.githubusercontent.com/assets/10451063/13806896/4a5ce1f8-eb56-11e5-85e6-28c4734ed9ef.PNG)

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-16 09:15
Interesting. Couldn't reproduce with with chrome's window size emulator, but will check it back at work against some devices.

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-16 09:21
Okay, this is reproduceable on saucelabs. I'll gather some more information and open a ticket on the main repo. Will close it then here. Good call @girishla

**Comment by girishla** [comment] 2016-03-16 09:22
Great, ta

**Comment by girishla** [comment] 2016-03-16 09:23
will let you close this when appropriate.

**Comment by benjamingr** [comment] 2016-03-16 09:47
They're scrollable to the right and behave exactly like code comments in GitHub and StackOverflow. I think the current behavior is fine.

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-16 09:48
Nah, he doesn't mean the codeblocks, but that you can't scroll past a certain point.

iOS 9.2, iPhone 6, process.html https://saucelabs.com/beta/tests/e2c86c418a5646bab619e9c4b4e2a6c7/watch
iOS 8.4, iPhone 6, stream.html https://saucelabs.com/beta/tests/fdc9c31581a24841bd8688555374f7f9/watch
iOS 9.2, iPhone 6, stream.html https://saucelabs.com/beta/tests/9e1d5547403b4ffd9f4f01ff9bf4d968/watch

**Comment by benjamingr** [comment] 2016-03-16 09:58
I tested on a real device and I can scroll all the way down - when I reach code blocks I have to stop scrolling and then resume it from a point that is not in the code block which is annoying. 

I think this happens because the scrolling gets "stuck" on the code block - we can fix this by listening to the scroll event and handling this case.

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-16 10:15
Could you be more precise please. Hardware, OS, Page? Because it's very easy to reproduce the faulty behaviour at sauce labs tbh.

**Comment by benjamingr** [comment] 2016-03-16 10:38
Sure - It's faulty, but I can scroll down. This is a real iPhone 6 with iOS 9.2 (haven't upgraded since).

**Comment by stevemao** [comment] 2016-03-16 12:04
I never had good experience viewing docs on my phone and I gave up... If there is any good third party docs viewer we could probably learn from it.

**Comment by eljefedelrodeodeljefe** [comment] 2016-03-23 09:57
Closed in favor for nodejs/node#5861 Thanks for reporting!

**Closed as completed by eljefedelrodeodeljefe** 2016-03-23 09:57 UTC

**Comment by girishla** [comment] 2016-03-23 10:12
Thanks for fixing!

**Comment by Knighton910** [comment] 2016-03-23 18:07
+1
