### ISSUE TITLE
.read() stream not fully explained 

### ISSUE THREAD

**Issue by davidgatti** [nodejs/docs#113] opened 2016-11-13 15:10 UTC
Hello,

The following sentence can be found in the documentation:

> In general, it is recommended that developers avoid the use of the `readable` event and the readable.read() method in favor of using either readable.pipe() or the 'data' event.

It is related to the [readable.read([size])](https://nodejs.org/api/stream.html#stream_readable_read_size) section. Sadly there is no explanation of why that is. I would love to learn why I should not use `readable` 🙂.

**Comment by davidgatti** [comment] 2017-01-05 14:17
Anyone?

**Comment by sam-github** [comment] 2017-01-09 19:27
Pipe because it supports back-pressure.

**Comment by davidgatti** [comment] 2017-01-10 13:55
🤔 Hmm that answer assumes to much of me. If you had a longer moment could you write a little more to give a more clear explanation. I would be truly grateful.

**Comment by sam-github** [comment] 2017-01-10 18:55
https://howtonode.org/streams-explained

I'm leaving this open, because it potentially indicates missing info in the docs, but this is not a place to ask for help understanding node, please use https://github.com/nodejs/help.

**Comment by davidgatti** [comment] 2017-01-10 19:19
I think I know one or two things about stream ;) https://github.com/davidgatti/How-to-Understand-Streams-in-NodeJS. Anyway confusing documentation, no explanation given - o well, lets move on ;)

**Comment by sam-github** [comment] 2017-01-10 19:36
@davidgatti I don't understand why you are asking questions about backpressure when you describe it here: https://github.com/davidgatti/How-to-Understand-Streams-in-NodeJS#the-best-use-case-of-a-stream-in-nodejs

Was it just to point out the docs don't describe it well?

Docs needs knowledgable contributors, please consider contributing your document as an initial "guide" to streams, or otherwise getting involved in the working group.

**Comment by sam-github** [comment] 2017-01-10 19:38
Actually, I will close this as a duplicate of https://github.com/nodejs/docs/issues/25

**Closed as completed by sam-github** 2017-01-10 19:38 UTC

**Comment by gibfahn** [comment] 2017-01-11 15:32
+1 to having more knowledgeable non-core people helping out with docs, @davidgatti if you'd be interested in contributing to a User guide on streams (as discussed in #25) that'd be great.

**Comment by davidgatti** [comment] 2017-01-11 15:35
Sure, but 

- I need to refresh my memory why I created this issue, it was a while back
- I'll still need to understand the developer thinking to then take what info and convert it in to something anyone will be able to understand.

I'll be back 🕶
